import { Router } from "express";
import { z } from "zod";
import type { AuthenticatedRequest } from "../middleware/auth.js";
import { getSupabaseAdmin } from "../services/supabase.js";

const sourceInput = z.object({ name: z.string().trim().min(1).max(120), sourceType: z.enum(["text", "url"]), content: z.string().max(50000).default(""), sourceUrl: z.string().url().max(2000).nullable().default(null) });
export const knowledgeRouter = Router();
knowledgeRouter.get("/", async (request: AuthenticatedRequest, response, next) => { try { const { data, error } = await getSupabaseAdmin().from("knowledge_sources").select("*, ai_agent_knowledge(agent_id)").eq("user_id", request.userId).order("updated_at", { ascending: false }); if (error) throw error; response.json(data); } catch (error) { next(error); } });
knowledgeRouter.post("/", async (request: AuthenticatedRequest, response, next) => { const parsed = sourceInput.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid knowledge source", fields: parsed.error.flatten().fieldErrors }); try { const input = parsed.data; if (input.sourceType === "text" && !input.content.trim()) return response.status(400).json({ error: "Text knowledge must include content" }); const { data, error } = await getSupabaseAdmin().from("knowledge_sources").insert({ user_id: request.userId, name: input.name, source_type: input.sourceType, content: input.content, source_url: input.sourceUrl }).select().single(); if (error) throw error; response.status(201).json(data); } catch (error) { next(error); } });
knowledgeRouter.patch("/:id", async (request: AuthenticatedRequest, response, next) => { const parsed = sourceInput.partial().safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid knowledge source" }); try { const input = parsed.data; const { data, error } = await getSupabaseAdmin().from("knowledge_sources").update({ ...(input.name !== undefined ? { name: input.name } : {}), ...(input.content !== undefined ? { content: input.content } : {}), ...(input.sourceUrl !== undefined ? { source_url: input.sourceUrl } : {}), updated_at: new Date().toISOString() }).eq("id", request.params.id).eq("user_id", request.userId).select().single(); if (error) throw error; response.json(data); } catch (error) { next(error); } });
knowledgeRouter.delete("/:id", async (request: AuthenticatedRequest, response, next) => { try { const { error } = await getSupabaseAdmin().from("knowledge_sources").delete().eq("id", request.params.id).eq("user_id", request.userId); if (error) throw error; response.status(204).send(); } catch (error) { next(error); } });
