import { Router } from "express";
import { z } from "zod";
import type { AuthenticatedRequest } from "../middleware/auth.js";
import { getSupabaseAdmin } from "../services/supabase.js";
import { claimConfiguredNumberForUser, releaseNumber } from "../services/telephony/TelnyxNumberService.js";
import { isAdministrator } from "../middleware/admin.js";

export const numbersRouter = Router();
const updateInput = z.object({ friendlyName: z.string().trim().max(120).nullable().optional(), agentId: z.string().uuid().nullable().optional() });
numbersRouter.get("/", async (request: AuthenticatedRequest, response, next) => { try { const database = getSupabaseAdmin(); let { data, error } = await database.from("phone_numbers").select("*, ai_agents(name)").eq("user_id", request.userId).order("created_at", { ascending: false }); if (error) throw error; if (!data?.length && request.userId && await isAdministrator(request.userId, request.userEmail)) { await claimConfiguredNumberForUser(request.userId); const refreshed = await database.from("phone_numbers").select("*, ai_agents(name)").eq("user_id", request.userId).order("created_at", { ascending: false }); if (refreshed.error) throw refreshed.error; data = refreshed.data; } response.json(data ?? []); } catch (error) { next(error); } });
numbersRouter.patch("/:id", async (request: AuthenticatedRequest, response, next) => { const parsed = updateInput.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid number configuration" }); try { const input = parsed.data; if (input.agentId) { const owned = await getSupabaseAdmin().from("ai_agents").select("id").eq("id", input.agentId).eq("user_id", request.userId).maybeSingle(); if (owned.error) throw owned.error; if (!owned.data) return response.status(400).json({ error: "That agent is not available" }); } const { data, error } = await getSupabaseAdmin().from("phone_numbers").update({ ...(input.friendlyName !== undefined ? { friendly_name: input.friendlyName } : {}), ...(input.agentId !== undefined ? { agent_id: input.agentId } : {}) }).eq("id", request.params.id).eq("user_id", request.userId).select("*, ai_agents(name)").single(); if (error) throw error; response.json(data); } catch (error) { next(error); } });
numbersRouter.post("/:id/default", async (request: AuthenticatedRequest, response, next) => { try { const database = getSupabaseAdmin(); const owned = await database.from("phone_numbers").select("id").eq("id", request.params.id).eq("user_id", request.userId).eq("provisioning_status", "active").maybeSingle(); if (owned.error) throw owned.error; if (!owned.data) return response.status(404).json({ error: "Number not found" }); const cleared = await database.from("phone_numbers").update({ is_default: false, updated_at: new Date().toISOString() }).eq("user_id", request.userId).eq("is_default", true); if (cleared.error) throw cleared.error; const { data, error } = await database.from("phone_numbers").update({ is_default: true, updated_at: new Date().toISOString() }).eq("id", request.params.id).select().single(); if (error) throw error; response.json(data); } catch (error) { next(error); } });
numbersRouter.delete("/:id", async (request: AuthenticatedRequest, response, next) => { try { const database = getSupabaseAdmin(); const { data: number, error } = await database.from("phone_numbers").select("id,telnyx_phone_number_id,provider_number_id").eq("id", request.params.id).eq("user_id", request.userId).eq("provisioning_status", "active").maybeSingle(); if (error) throw error; if (!number) return response.status(404).json({ error: "Number not found" }); await database.from("phone_numbers").update({ provisioning_status: "releasing", status: "releasing", updated_at: new Date().toISOString() }).eq("id", number.id); try { await releaseNumber(number.telnyx_phone_number_id ?? number.provider_number_id); } catch (releaseError) { await database.from("phone_numbers").update({ provisioning_status: "failed", status: "active", updated_at: new Date().toISOString() }).eq("id", number.id); throw releaseError; } const { data: released, error: releaseError } = await database.from("phone_numbers").update({ provisioning_status: "released", status: "released", is_default: false, released_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", number.id).select().single(); if (releaseError) throw releaseError; response.json(released); } catch (error) { next(error); } });
