import { Router } from "express";
import { z } from "zod";
import type { AuthenticatedRequest } from "../middleware/auth.js";
import { getSupabaseAdmin } from "../services/supabase.js";

export const supportRouter = Router();
const ticketInput = z.object({ subject: z.string().trim().min(3).max(160), category: z.string().trim().max(60).default("general"), priority: z.enum(["low", "normal", "high", "urgent"]).default("normal"), body: z.string().trim().min(10).max(10000) });
const messageInput = z.object({ body: z.string().trim().min(1).max(10000) });
supportRouter.get("/tickets", async (request: AuthenticatedRequest, response, next) => { try { const database = getSupabaseAdmin(); const { data, error } = await database.from("support_tickets").select("*, support_messages(id, body, author_type, created_at)").eq("user_id", request.userId).order("updated_at", { ascending: false }); if (error) throw error; response.json(data); } catch (error) { next(error); } });
supportRouter.post("/tickets", async (request: AuthenticatedRequest, response, next) => { const parsed = ticketInput.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid support ticket", fields: parsed.error.flatten().fieldErrors }); try { const database = getSupabaseAdmin(); const input = parsed.data; const ticket = await database.from("support_tickets").insert({ user_id: request.userId, subject: input.subject, priority: input.priority }).select().single(); if (ticket.error) throw ticket.error; const message = await database.from("support_messages").insert({ ticket_id: ticket.data.id, author_id: request.userId, author_type: "customer", body: `[${input.category}] ${input.body}`, delivery_status: "queued" }).select().single(); if (message.error) throw message.error; response.status(201).json({ ...ticket.data, support_messages: [message.data] }); } catch (error) { next(error); } });
supportRouter.post("/tickets/:id/messages", async (request: AuthenticatedRequest, response, next) => { const parsed = messageInput.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Message cannot be empty" }); try { const database = getSupabaseAdmin(); const owned = await database.from("support_tickets").select("id").eq("id", request.params.id).eq("user_id", request.userId).maybeSingle(); if (owned.error) throw owned.error; if (!owned.data) return response.status(404).json({ error: "Ticket not found" }); const message = await database.from("support_messages").insert({ ticket_id: request.params.id, author_id: request.userId, author_type: "customer", body: parsed.data.body, delivery_status: "queued" }).select().single(); if (message.error) throw message.error; await database.from("support_tickets").update({ last_message_at: new Date().toISOString(), updated_at: new Date().toISOString(), status: "open" }).eq("id", request.params.id); response.status(201).json(message.data); } catch (error) { next(error); } });
