import { Router } from "express";
import { z } from "zod";
import type { AuthenticatedRequest } from "../middleware/auth.js";
import { getSupabaseAdmin } from "../services/supabase.js";

const taskInput = z.object({ title: z.string().trim().min(1).max(120), phoneNumber: z.string().trim().regex(/^\+[1-9]\d{6,14}$/, "Destination must be an E.164 phone number"), objective: z.string().trim().min(1).max(4000), agentId: z.string().uuid().nullable().default(null), contactId: z.string().uuid().nullable().default(null), importantInformation: z.string().trim().max(4000).nullable().default(null), restrictions: z.string().trim().max(4000).nullable().default(null), preferredTone: z.string().trim().min(1).max(80).default("Professional"), requiredOutcome: z.string().trim().max(1000).nullable().default(null), informationToExtract: z.string().trim().max(1000).nullable().default(null), scheduledAt: z.string().datetime().nullable().default(null), maximumDurationMinutes: z.coerce.number().int().min(1).max(180).default(15), maxAttempts: z.coerce.number().int().min(1).max(10).default(3) });
export const tasksRouter = Router();
tasksRouter.get("/", async (request: AuthenticatedRequest, response, next) => { try { const { data, error } = await getSupabaseAdmin().from("call_tasks").select("*, ai_agents(name)").eq("user_id", request.userId).order("created_at", { ascending: false }); if (error) throw error; response.json(data); } catch (error) { next(error); } });
tasksRouter.post("/", async (request: AuthenticatedRequest, response, next) => { const parsed = taskInput.safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid task details", fields: parsed.error.flatten().fieldErrors }); try { const input = parsed.data; const database = getSupabaseAdmin(); if (input.agentId) { const agent = await database.from("ai_agents").select("id").eq("id", input.agentId).eq("user_id", request.userId).maybeSingle(); if (agent.error) throw agent.error; if (!agent.data) return response.status(400).json({ error: "That AI agent is not available" }); } if (input.contactId) { const contact = await database.from("contacts").select("id").eq("id", input.contactId).eq("user_id", request.userId).maybeSingle(); if (contact.error) throw contact.error; if (!contact.data) return response.status(400).json({ error: "That contact is not available" }); } const { data, error } = await database.from("call_tasks").insert({ user_id: request.userId, title: input.title, phone_number: input.phoneNumber, objective: input.objective, agent_id: input.agentId, contact_id: input.contactId, important_information: input.importantInformation, restrictions: input.restrictions, preferred_tone: input.preferredTone, required_outcome: input.requiredOutcome, information_to_extract: input.informationToExtract, scheduled_at: input.scheduledAt, maximum_duration_minutes: input.maximumDurationMinutes, max_attempts: input.maxAttempts, status: input.scheduledAt ? "scheduled" : "draft" }).select().single(); if (error) throw error; response.status(201).json(data); } catch (error) { next(error); } });
tasksRouter.patch("/:id/status", async (request: AuthenticatedRequest, response, next) => { const parsed = z.object({ status: z.enum(["draft", "scheduled", "cancelled"]) }).safeParse(request.body); if (!parsed.success) return response.status(400).json({ error: "Invalid task status" }); try { const { data, error } = await getSupabaseAdmin().from("call_tasks").update({ status: parsed.data.status, updated_at: new Date().toISOString() }).eq("id", request.params.id).eq("user_id", request.userId).select().single(); if (error) throw error; response.json(data); } catch (error) { next(error); } });